In [90]:
import pandas as pd
import emoji

In [9]:
df_train = pd.read_csv("data/hackathon_loreal_train_set.csv")
df_train

Unnamed: 0                                               text  \
0               0  Skeeterbytes wrote: Bassam Guy wrote: I don't ...   
1               1  Refueling before the long week 🍵 - You’re mean...   
2               2  Just in case no one has told you today YOU ARE...   
3               3  Do not forget to get some sunshine safely if y...   
4               4  Abstract Background Humans have dramatically c...   
...           ...                                                ...   
10567       13209  ☑ Day: 273 Outifit: Thor (Gold Foil) Back Blin...   
10568       13210  In order to study the various trends and patte...   
10569       13212  This brand has not yet registered with Influen...   
10570       13213  here is my regime get rid of any acne scars an...   
10571       13214  It's true, I used to work as a caddie at Trump...   

       skincare  hair  make-up  other  index  
0           0.0   0.0      0.0    1.0      0  
1           0.0   0.0      0.0    1.0      1  
2           0.0   0.0      1.0    0.0      2  
3           0.0   0.0      0.0    1.0      3  
4           0.0   0.0      0.0    1.0      4  
...         ...   ...      ...    ...    ...  
10567       0.0   0.0      0.0    1.0  13209  
10568       0.0   0.0      0.0    1.0  13210  
10569       0.0   0.0      0.0    1.0  13212  
10570       1.0   0.0      0.0    0.0  13213  
10571       0.0   0.0      0.0    1.0  13214  

[10572 rows x 7 columns]

# watch data

In [10]:
df_train.columns

Index(['Unnamed: 0', 'text', 'skincare', 'hair', 'make-up', 'other', 'index'], dtype='object')

In [11]:
df = df_train[df_train['Unnamed: 0'] != df_train['index']]
df

Empty DataFrame
Columns: [Unnamed: 0, text, skincare, hair, make-up, other, index]
Index: []

# delete one columns

In [12]:
df_train = df_train.drop(['Unnamed: 0'], axis = 1)
df_train

text  skincare  hair  \
0      Skeeterbytes wrote: Bassam Guy wrote: I don't ...       0.0   0.0   
1      Refueling before the long week 🍵 - You’re mean...       0.0   0.0   
2      Just in case no one has told you today YOU ARE...       0.0   0.0   
3      Do not forget to get some sunshine safely if y...       0.0   0.0   
4      Abstract Background Humans have dramatically c...       0.0   0.0   
...                                                  ...       ...   ...   
10567  ☑ Day: 273 Outifit: Thor (Gold Foil) Back Blin...       0.0   0.0   
10568  In order to study the various trends and patte...       0.0   0.0   
10569  This brand has not yet registered with Influen...       0.0   0.0   
10570  here is my regime get rid of any acne scars an...       1.0   0.0   
10571  It's true, I used to work as a caddie at Trump...       0.0   0.0   

       make-up  other  index  
0          0.0    1.0      0  
1          0.0    1.0      1  
2          1.0    0.0      2  
3          0.0    1.0      3  
4          0.0    1.0      4  
...        ...    ...    ...  
10567      0.0    1.0  13209  
10568      0.0    1.0  13210  
10569      0.0    1.0  13212  
10570      0.0    0.0  13213  
10571      0.0    1.0  13214  

[10572 rows x 6 columns]

# preprocessing one text

In [16]:
import pandas as pd

import nltk
from nltk.corpus import wordnet
from nltk.corpus import stopwords
from nltk.metrics import ConfusionMatrix
from nltk.stem.snowball import SnowballStemmer

from nltk import word_tokenize, WordNetLemmatizer, PorterStemmer
from nltk import pos_tag
from nltk import ngrams
from nltk import sent_tokenize

from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lucas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [106]:
Onetext = df_train['text'].iloc[1]
Onetext

'Refueling before the long week 🍵 - You’re meant to Drink it, but I prefer it in my 🍵 From to , matcha is a natural powder of freshly ground leaves! ✅thanks to its numerous antioxidant benefits! ✅Including it in your beauty routine requires very little time and effort to see benefits ✅ The best part of it is that it’s already in your cupboard and doubles as a delicious drink? It really doesn’t get better than this! 🛒 Matcha tea purchased from my favorite online store faithfultonature'

In [112]:
from emoji.unicode_codes import UNICODE_EMOJI
import regex

def extract_emojis(s):
  for c in s:
    if c in UNICODE_EMOJI:
        print(True)
extract_emojis(Onetext)

In [92]:
OnetextLower = Onetext.lower()
OnetextLower

'refueling before the long week 🍵 - you’re meant to drink it, but i prefer it in my 🍵 from to , matcha is a natural powder of freshly ground leaves! ✅thanks to its numerous antioxidant benefits! ✅including it in your beauty routine requires very little time and effort to see benefits ✅ the best part of it is that it’s already in your cupboard and doubles as a delicious drink? it really doesn’t get better than this! 🛒 matcha tea purchased from my favorite online store faithfultonature'

In [93]:
tokenizeSingletext = word_tokenize(OnetextLower)
tokenizeSingletext

['refueling',
 'before',
 'the',
 'long',
 'week',
 '🍵',
 '-',
 'you',
 '’',
 're',
 'meant',
 'to',
 'drink',
 'it',
 ',',
 'but',
 'i',
 'prefer',
 'it',
 'in',
 'my',
 '🍵',
 'from',
 'to',
 ',',
 'matcha',
 'is',
 'a',
 'natural',
 'powder',
 'of',
 'freshly',
 'ground',
 'leaves',
 '!',
 '✅thanks',
 'to',
 'its',
 'numerous',
 'antioxidant',
 'benefits',
 '!',
 '✅including',
 'it',
 'in',
 'your',
 'beauty',
 'routine',
 'requires',
 'very',
 'little',
 'time',
 'and',
 'effort',
 'to',
 'see',
 'benefits',
 '✅',
 'the',
 'best',
 'part',
 'of',
 'it',
 'is',
 'that',
 'it',
 '’',
 's',
 'already',
 'in',
 'your',
 'cupboard',
 'and',
 'doubles',
 'as',
 'a',
 'delicious',
 'drink',
 '?',
 'it',
 'really',
 'doesn',
 '’',
 't',
 'get',
 'better',
 'than',
 'this',
 '!',
 '🛒',
 'matcha',
 'tea',
 'purchased',
 'from',
 'my',
 'favorite',
 'online',
 'store',
 'faithfultonature']

In [82]:
lemmatizer = WordNetLemmatizer()
lemmatizeSingleText = list(map(lemmatizer.lemmatize, tokenizeSingletext))
lemmatizeSingleText

['refueling',
 'before',
 'the',
 'long',
 'week',
 '🍵',
 '-',
 'you',
 '’',
 're',
 'meant',
 'to',
 'drink',
 'it',
 ',',
 'but',
 'i',
 'prefer',
 'it',
 'in',
 'my',
 '🍵',
 'from',
 'to',
 ',',
 'matcha',
 'is',
 'a',
 'natural',
 'powder',
 'of',
 'freshly',
 'ground',
 'leaf',
 '!',
 '✅thanks',
 'to',
 'it',
 'numerous',
 'antioxidant',
 'benefit',
 '!',
 '✅including',
 'it',
 'in',
 'your',
 'beauty',
 'routine',
 'requires',
 'very',
 'little',
 'time',
 'and',
 'effort',
 'to',
 'see',
 'benefit',
 '✅',
 'the',
 'best',
 'part',
 'of',
 'it',
 'is',
 'that',
 'it',
 '’',
 's',
 'already',
 'in',
 'your',
 'cupboard',
 'and',
 'double',
 'a',
 'a',
 'delicious',
 'drink',
 '?',
 'it',
 'really',
 'doesn',
 '’',
 't',
 'get',
 'better',
 'than',
 'this',
 '!',
 '🛒',
 'matcha',
 'tea',
 'purchased',
 'from',
 'my',
 'favorite',
 'online',
 'store',
 'faithfultonature']

In [87]:
stop_punctuation = [':', '(', ')', '/', '|', ',', ']', ';',
                    '.', '*', '#', '"', '&', '~', '``',
                    '-', '_', '\\', '@','?','!','\'', '[', '🍵']
TextCleanPonctuation = [word for word in lemmatizeSingleText if word not in stop_punctuation]
TextCleanPonctuation

['refueling',
 'before',
 'the',
 'long',
 'week',
 'you',
 '’',
 're',
 'meant',
 'to',
 'drink',
 'it',
 'but',
 'i',
 'prefer',
 'it',
 'in',
 'my',
 'from',
 'to',
 'matcha',
 'is',
 'a',
 'natural',
 'powder',
 'of',
 'freshly',
 'ground',
 'leaf',
 '✅thanks',
 'to',
 'it',
 'numerous',
 'antioxidant',
 'benefit',
 '✅including',
 'it',
 'in',
 'your',
 'beauty',
 'routine',
 'requires',
 'very',
 'little',
 'time',
 'and',
 'effort',
 'to',
 'see',
 'benefit',
 '✅',
 'the',
 'best',
 'part',
 'of',
 'it',
 'is',
 'that',
 'it',
 '’',
 's',
 'already',
 'in',
 'your',
 'cupboard',
 'and',
 'double',
 'a',
 'a',
 'delicious',
 'drink',
 'it',
 'really',
 'doesn',
 '’',
 't',
 'get',
 'better',
 'than',
 'this',
 '🛒',
 'matcha',
 'tea',
 'purchased',
 'from',
 'my',
 'favorite',
 'online',
 'store',
 'faithfultonature']

In [86]:
stoplist = stopwords.words('english')
TextCleanPonctuationWord = [word for word in TextCleanPonctuation if word not in stoplist]
TextCleanPonctuationWord

['refueling',
 'long',
 'week',
 '🍵',
 '’',
 'meant',
 'drink',
 'prefer',
 '🍵',
 'matcha',
 'natural',
 'powder',
 'freshly',
 'ground',
 'leaf',
 '✅thanks',
 'numerous',
 'antioxidant',
 'benefit',
 '✅including',
 'beauty',
 'routine',
 'requires',
 'little',
 'time',
 'effort',
 'see',
 'benefit',
 '✅',
 'best',
 'part',
 '’',
 'already',
 'cupboard',
 'double',
 'delicious',
 'drink',
 'really',
 '’',
 'get',
 'better',
 '🛒',
 'matcha',
 'tea',
 'purchased',
 'favorite',
 'online',
 'store',
 'faithfultonature']

# functions

In [23]:
def preprocessing(singleText):
    lemmatizer = WordNetLemmatizer()
    stop_punctuation = [':', '(', ')', '/', '|', ',', ']', ';',
                    '.', '*', '#', '"', '&', '~', '``',
                    '-', '_', '\\', '@','?','!','\'', '[']
    stoplist = stopwords.words('english')

    LowerSingleText = singleText.lower()
    tokenizeSingletext = word_tokenize(LowerSingleText)
    lemmatizeSingleText = list(map(lemmatizer.lemmatize, tokenizeSingletext))
    
    TextCleanPonctuation = [word for word in lemmatizeSingleText if word not in stop_punctuation and word not in stoplist]

    return TextCleanPonctuation

def clean_text(text):
    text_preprocessed = preprocessing(text)
    
    clean_mail = [word for word in text_preprocessed if word not in stop_punctuation and not word in stoplist]
    return ' '.join(clean_mail)

In [24]:
result = clean_text(df_train["text"].iloc[0])
result

"skeeterbytes wrote bassam guy wrote n't anything longer 60mm except $ 99 plastic fantastic '' 40-150. 've never really tried avian photography would like get decent shot unlike opportunity arises used c-af+tr retrospect since turkey lawyer refused fly despite plea would s-af done better mf peaking magnify exposed lawyer dressed dark suit bright cloudy sky meteorologist say smoke remnant ca northern va wa +2 +2.5 ev much encouraged chroma 'm great judging distance would say wa 35+ meter away pretty intense purple fringing lightroom ha effective one-click remover 'm sure software ha hard control know panasonic 7-14 4 never use c-af+tr preferring standard c-af s-af instance s-af fine attorney n't going anywhere pay bill get s-af+magnify allow tweak focus plus want stop lens bit sharpen except 7-14 nothing else f2.8 5.6 seems stopped 'll watch tried magnify wa shaky long fl 'll try lower scale factor also raise shutter speed freeze flapping 're iso200 's good lens within realm 40-150 pro 

# On applique cela pour toute la base de donnée

In [26]:
df_train["clean_content"] = df_train.text.apply(clean_text)
df_train["clean_content"]

0        skeeterbytes wrote bassam guy wrote n't anythi...
1        refueling long week 🍵 ’ meant drink prefer 🍵 m...
2        case one ha told today strong beautiful love 🌹...
3        forget get sunshine safely ☀️ head link bio se...
4        abstract background human dramatically changed...
                               ...                        
10567    ☑ day 273 outifit thor gold foil back bling et...
10568    order study various trend pattern prevailing c...
10569    brand ha yet registered influenster work brand...
10570    regime get rid acne scar get way smoother heal...
10571    's true used work caddie trump national nj don...
Name: clean_content, Length: 10572, dtype: object

# vectorization

In [41]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

## separate

In [66]:
X = df_train_clean['clean_content']
Y = df_train_clean.drop(['clean_content', 'index'], axis = 1)
X

0        skeeterbytes wrote bassam guy wrote n't anythi...
1        refueling long week 🍵 ’ meant drink prefer 🍵 m...
2        case one ha told today strong beautiful love 🌹...
3        forget get sunshine safely ☀️ head link bio se...
4        abstract background human dramatically changed...
                               ...                        
10567    ☑ day 273 outifit thor gold foil back bling et...
10568    order study various trend pattern prevailing c...
10569    brand ha yet registered influenster work brand...
10570    regime get rid acne scar get way smoother heal...
10571    's true used work caddie trump national nj don...
Name: clean_content, Length: 10572, dtype: object

In [67]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4)

In [72]:
pipe = make_pipeline(CountVectorizer(), TfidfTransformer())
pipe.fit(x_train)
feat_train = pipe.transform(x_train)
feat_train

<1x71330 sparse matrix of type '<class 'numpy.float64'>'
	with 71 stored elements in Compressed Sparse Row format>

In [69]:
feat_train

<8457x71330 sparse matrix of type '<class 'numpy.float64'>'
	with 704785 stored elements in Compressed Sparse Row format>

# Model

In [70]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=50)
clf.fit(feat_train, y_train)

RandomForestClassifier(n_estimators=50)

In [113]:
feat_test = pipe.transform(x_test)
clf.score(feat_test, y_test) 

0.99


# visualisation result

In [65]:
from sklearn.metrics import roc_auc_score, roc_curve, auc
score = clf.predict_proba(feat_test)
score
#fpr, tpr, th = roc_curve(y_list_test, score[:, 1])

[array([[1.  , 0.  ],
        [0.96, 0.04],
        [0.98, 0.02],
        ...,
        [0.9 , 0.1 ],
        [0.92, 0.08],
        [1.  , 0.  ]]),
 array([[0.98      , 0.02      ],
        [0.76666667, 0.23333333],
        [1.        , 0.        ],
        ...,
        [0.92      , 0.08      ],
        [0.975     , 0.025     ],
        [0.97      , 0.03      ]]),
 array([[0.96, 0.04],
        [0.86, 0.14],
        [0.96, 0.04],
        ...,
        [0.94, 0.06],
        [0.98, 0.02],
        [1.  , 0.  ]]),
 array([[0.06      , 0.94      ],
        [0.39333333, 0.60666667],
        [0.06      , 0.94      ],
        ...,
        [0.24      , 0.76      ],
        [0.105     , 0.895     ],
        [0.03      , 0.97      ]])]

In [61]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(4,4))
ax.plot([0, 1], [0, 1], 'k--')
aucf = auc(fpr, tpr)
ax.plot(fpr, tpr, label='auc=%1.5f' % aucf)
ax.set_title('Courbe ROC - classifieur de sentiments')
ax.legend();

NameError: name 'fpr' is not defined